# Markdown linting configuration
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true

# MD013: Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# MD033: Allow inline HTML (for badges, etc.)
MD033: false

# MD041: First line in file should be a top level heading
MD041: false
