# Enable commit-msg hooks for conventional commit validation
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  # Standard pre-commit hooks (v6.0.0 - latest 2025)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--indent=2']
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: detect-private-key
      - id: check-executables-have-shebangs

  # Markdown linting for documentation quality
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        args: ['--config', '.markdownlint.yaml', '--fix']

  # Conventional commit message validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - feat
          - fix
          - docs
          - style
          - refactor
          - perf
          - test
          - build
          - ci
          - chore
          - revert

  # Elixir-specific local hooks
  - repo: local
    hooks:
      - id: mix-format
        name: Mix Format Check
        entry: mix format --check-formatted
        language: system
        types: [elixir]
        pass_filenames: false

      - id: mix-credo
        name: Credo Static Analysis
        entry: mix credo --strict
        language: system
        types: [elixir]
        pass_filenames: false

      - id: mix-compile
        name: Mix Compile (warnings as errors)
        entry: mix compile --warnings-as-errors
        language: system
        types: [elixir]
        pass_filenames: false

      - id: mix-test
        name: Mix Test
        entry: mix test
        language: system
        types: [elixir]
        pass_filenames: false
